### ISSUE TITLE
ImageCache.getBitmap() causing OutOfMemoryError

### ISSUE THREAD

**Issue by istashak** [mttkay/droid-fu#41]
This is a similar issue to a previously closed bug.  While using the WebImageView, which uses ImageLoader.start(...) I get the following OutOfMemoryError.

Here's the exception stack:

E AndroidRuntime: java.lang.OutOfMemoryError: bitmap size exceeds VM budget
E AndroidRuntime: at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
E AndroidRuntime: at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:392)
E AndroidRuntime: at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:405)
E AndroidRuntime: at com.github.droidfu.cachefu.ImageCache.getBitmap(ImageCache.java:67)
E AndroidRuntime: at com.github.droidfu.imageloader.ImageLoader.setOrLoadImage(ImageLoader.java:185)
E AndroidRuntime: at com.github.droidfu.imageloader.ImageLoader.start(ImageLoader.java:178)
E AndroidRuntime: at com.github.droidfu.widgets.WebImageView.loadImage(WebImageView.java:161)

**Comment by istashak** [comment]
Also, note that I'm using low resolution PNGs in a ListView (Images range in size from about 5 to 13 K with the average somewhere in the middle).  It seems that garbage collection can't keep up with the speed of memory consumption.

**Comment by futtetennista** [comment]
Could you please tell what branch/commit you're using?
