### ISSUE TITLE
Nullpointer in AbstractCache

### ISSUE THREAD

**Issue by jjfster** [mttkay/droid-fu#47]
I don't get very many of these reports, but they are still showing up:

Caused by: java.lang.NullPointerException
at com.github.droidfu.cachefu.AbstractCache.enableDiskCache(AbstractCache.java:137)
at com.github.droidfu.imageloader.ImageLoader.initialize(ImageLoader.java:100)

which is the appcontext assignment from ImageLoader's context:

AbstractCache:  
  public boolean enableDiskCache(Context context, int storageDevice) {

```
    Context appContext = context.getApplicationContext();
```

ImageLoader:
   public static synchronized void initialize(Context context) {
        if (executor == null) {
            executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(DEFAULT_POOL_SIZE);
        }
        if (imageCache == null) {
            imageCache = new ImageCache(25, expirationInMinutes, DEFAULT_POOL_SIZE);
            imageCache.enableDiskCache(context, ImageCache.DISK_CACHE_SDCARD);
        }
    }

Could it just be the app is running low on memory and the context is null?  I set this onCreate for the parent class, so maybe for some reason the context is not available?

I made one change in EnableDiskCache whereby I would just return false if the context was null, but it was causing all images to stop delivering for periods of time for some testers.

**Comment by jjfster** [comment]
Never mind.  I found the issue.  This was in an adapter and the context wasn't always being assigned before the imageloader.initialize was called.
